### PR TITLE
Fixed Carthage issue

### PR DESCRIPTION
**Pull request by AnanthaKrish**
Updated the pods with latest BMSCore SDK

### CODE REVIEW

**Comment by SachinLavista911** [comment]
I am not able to get the following pods BMSAnalyticsAPI (1.0.1) BMSCore (1.0.0) BMSPush (1.0.3) . How can I get the latest pod for the above i.e to BMSAnalyticsAPI (2.2.0) BMSCore (2.3.1) BMSPush (3.1.1).

**Comment by AnanthaKrish** [comment]
Hi @SachinLavista911 , Are you using carthage or Cocoapods ?

**Comment by SachinLavista911** [comment]
Hi Anantha,
I am using Cocoapods  version 1.2.0.
After using your sample code given at
https://github.com/ibm-bluemix-mobile-services/bms-samples-swift-hellopush .
I did pod install and I only get the  BMSAnalyticsAPI (1.0.1) BMSCore
(1.0.0) BMSPush (1.0.3) screenshot (PFA  Screenshot -PodUpdate.png). But
that sample doesn't work and its gives a lot of swift 3 conversion errors.
In the given sample video :- https://www.youtube.com/watch?v=cOXjn3fuNG0,
after pod install , they get BMSAnalyticsAPI (2.2.0) BMSCore (2.3.1)
BMSPush (3.1.1) . (PFA Screenshot - SampleVideoPods.png) . How can I get
the latest pods ?


Can you please  help me to sort this issue . ? It's very critical

**Comment by AnanthaKrish** [comment]
Can you try `pod update`.. Your local pods seems to be old..

**Pull request merged**
